[tool.poetry]
name = "unsuckjs.com-coltrane"
version = "0.1.0"
description = ""
authors = ["adamghill <adamghill@yahoo.com>"]

[tool.poetry.dependencies]
python = "^3.10"
coltrane-web = {extras = ["deploy"], version = "<1"}
iso8601 = "^1.0.2"
django-cache-memoize = "^0.1.10"
python-benedict = "^0.25.2"
httpx = "^0.23.0"
gunicorn = "^20.1.0"
hiredis = "^2.0.0"
redis = "^4.4.4"

[tool.poetry.dev-dependencies]
isort = "^5.10.1"
black = "^22.6.0"
pytest = "^7.1.2"

[tool.poe.tasks]
r = { cmd = "poetry run coltrane play", help = "Start dev server" }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
